version: "3.3"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - 5432:5432
    restart: unless-stopped

    volumes:
      - ./_volumes/dev/postgres-data:/var/lib/postgresql/data
